### ISSUE TITLE
is this alternative to Unity Hub?

### ISSUE THREAD

**Issue by nvcken** [wooga/atlas-unity-version-manager#8]

**Comment by Larusso** [comment]
This will be a gradle plugin to allow installations of unity during build time with gradle.
This plugin uses a rust tool [unity-version-manager], which is also still under development.
This tools purpose is to install unity from command line and is hooked into Unity Hub.

At the moment this plugin and the [unity-version-manager] works only on mac-os. I strife for windows compatibility right after the first stable release and maybe linux as well.

[unity-version-manager]: https://github.com/Larusso/unity-version-manager

**Comment by cuongnv-ibl** [comment]
Cool, thanks

**Comment by nvcken** [comment]
Cool, thanks
